/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountTests
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Test]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Account
            //Assert.IsInstanceOfType<Account> (instance, "variable 'instance' is a Account");
        }


        /// <summary>
        /// Test the property 'AccountPanSuffix'
        /// </summary>
        [Test]
        public void AccountPanSuffixTest()
        {
            // TODO unit test for the property 'AccountPanSuffix'
        }
        /// <summary>
        /// Test the property 'FinancialAccountSuffix'
        /// </summary>
        [Test]
        public void FinancialAccountSuffixTest()
        {
            // TODO unit test for the property 'FinancialAccountSuffix'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'InterbankCardAssociationId'
        /// </summary>
        [Test]
        public void InterbankCardAssociationIdTest()
        {
            // TODO unit test for the property 'InterbankCardAssociationId'
        }
        /// <summary>
        /// Test the property 'InstitutionName'
        /// </summary>
        [Test]
        public void InstitutionNameTest()
        {
            // TODO unit test for the property 'InstitutionName'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'AlternateAccountIdentifierSuffix'
        /// </summary>
        [Test]
        public void AlternateAccountIdentifierSuffixTest()
        {
            // TODO unit test for the property 'AlternateAccountIdentifierSuffix'
        }
        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Test]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }

    }

}
