/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing ActivationMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActivationMethodTests
    {
        // TODO uncomment below to declare an instance variable for ActivationMethod
        //private ActivationMethod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActivationMethod
            //instance = new ActivationMethod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActivationMethod
        /// </summary>
        [Test]
        public void ActivationMethodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ActivationMethod
            //Assert.IsInstanceOfType<ActivationMethod> (instance, "variable 'instance' is a ActivationMethod");
        }


        /// <summary>
        /// Test the property 'ActivationMethodType'
        /// </summary>
        [Test]
        public void ActivationMethodTypeTest()
        {
            // TODO unit test for the property 'ActivationMethodType'
        }
        /// <summary>
        /// Test the property 'ActivationMethodValue'
        /// </summary>
        [Test]
        public void ActivationMethodValueTest()
        {
            // TODO unit test for the property 'ActivationMethodValue'
        }
        /// <summary>
        /// Test the property 'ActivationMethodId'
        /// </summary>
        [Test]
        public void ActivationMethodIdTest()
        {
            // TODO unit test for the property 'ActivationMethodId'
        }
        /// <summary>
        /// Test the property 'ResendIndicator'
        /// </summary>
        [Test]
        public void ResendIndicatorTest()
        {
            // TODO unit test for the property 'ResendIndicator'
        }

    }

}
