/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing Device
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceTests
    {
        // TODO uncomment below to declare an instance variable for Device
        //private Device instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Device
            //instance = new Device();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Device
        /// </summary>
        [Test]
        public void DeviceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Device
            //Assert.IsInstanceOfType<Device> (instance, "variable 'instance' is a Device");
        }


        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'DeviceName'
        /// </summary>
        [Test]
        public void DeviceNameTest()
        {
            // TODO unit test for the property 'DeviceName'
        }
        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Test]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }
        /// <summary>
        /// Test the property 'SecureElementId'
        /// </summary>
        [Test]
        public void SecureElementIdTest()
        {
            // TODO unit test for the property 'SecureElementId'
        }

    }

}
