/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing Status
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatusTests
    {
        // TODO uncomment below to declare an instance variable for Status
        //private Status instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Status
            //instance = new Status();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Status
        /// </summary>
        [Test]
        public void StatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Status
            //Assert.IsInstanceOfType<Status> (instance, "variable 'instance' is a Status");
        }


        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Test]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'StatusDescription'
        /// </summary>
        [Test]
        public void StatusDescriptionTest()
        {
            // TODO unit test for the property 'StatusDescription'
        }
        /// <summary>
        /// Test the property 'StatusDateTime'
        /// </summary>
        [Test]
        public void StatusDateTimeTest()
        {
            // TODO unit test for the property 'StatusDateTime'
        }
        /// <summary>
        /// Test the property 'Initiator'
        /// </summary>
        [Test]
        public void InitiatorTest()
        {
            // TODO unit test for the property 'Initiator'
        }
        /// <summary>
        /// Test the property 'CommentId'
        /// </summary>
        [Test]
        public void CommentIdTest()
        {
            // TODO unit test for the property 'CommentId'
        }
        /// <summary>
        /// Test the property 'ReasonCode'
        /// </summary>
        [Test]
        public void ReasonCodeTest()
        {
            // TODO unit test for the property 'ReasonCode'
        }
        /// <summary>
        /// Test the property 'AuditInfo'
        /// </summary>
        [Test]
        public void AuditInfoTest()
        {
            // TODO unit test for the property 'AuditInfo'
        }

    }

}
