/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing SystemStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SystemStatusResponseTests
    {
        // TODO uncomment below to declare an instance variable for SystemStatusResponse
        //private SystemStatusResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SystemStatusResponse
            //instance = new SystemStatusResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SystemStatusResponse
        /// </summary>
        [Test]
        public void SystemStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SystemStatusResponse
            //Assert.IsInstanceOfType<SystemStatusResponse> (instance, "variable 'instance' is a SystemStatusResponse");
        }


        /// <summary>
        /// Test the property 'CommentText'
        /// </summary>
        [Test]
        public void CommentTextTest()
        {
            // TODO unit test for the property 'CommentText'
        }
        /// <summary>
        /// Test the property 'LastStatusDateTime'
        /// </summary>
        [Test]
        public void LastStatusDateTimeTest()
        {
            // TODO unit test for the property 'LastStatusDateTime'
        }

    }

}
