/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing TokenUnsuspendRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TokenUnsuspendRequestTests
    {
        // TODO uncomment below to declare an instance variable for TokenUnsuspendRequest
        //private TokenUnsuspendRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenUnsuspendRequest
            //instance = new TokenUnsuspendRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenUnsuspendRequest
        /// </summary>
        [Test]
        public void TokenUnsuspendRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TokenUnsuspendRequest
            //Assert.IsInstanceOfType<TokenUnsuspendRequest> (instance, "variable 'instance' is a TokenUnsuspendRequest");
        }


        /// <summary>
        /// Test the property 'TokenUniqueReference'
        /// </summary>
        [Test]
        public void TokenUniqueReferenceTest()
        {
            // TODO unit test for the property 'TokenUniqueReference'
        }
        /// <summary>
        /// Test the property 'CommentText'
        /// </summary>
        [Test]
        public void CommentTextTest()
        {
            // TODO unit test for the property 'CommentText'
        }
        /// <summary>
        /// Test the property 'ReasonCode'
        /// </summary>
        [Test]
        public void ReasonCodeTest()
        {
            // TODO unit test for the property 'ReasonCode'
        }
        /// <summary>
        /// Test the property 'AuditInfo'
        /// </summary>
        [Test]
        public void AuditInfoTest()
        {
            // TODO unit test for the property 'AuditInfo'
        }

    }

}
