/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing TokenUnsuspendResponseSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TokenUnsuspendResponseSchemaTests
    {
        // TODO uncomment below to declare an instance variable for TokenUnsuspendResponseSchema
        //private TokenUnsuspendResponseSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenUnsuspendResponseSchema
            //instance = new TokenUnsuspendResponseSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenUnsuspendResponseSchema
        /// </summary>
        [Test]
        public void TokenUnsuspendResponseSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TokenUnsuspendResponseSchema
            //Assert.IsInstanceOfType<TokenUnsuspendResponseSchema> (instance, "variable 'instance' is a TokenUnsuspendResponseSchema");
        }


        /// <summary>
        /// Test the property 'TokenUnsuspendResponse'
        /// </summary>
        [Test]
        public void TokenUnsuspendResponseTest()
        {
            // TODO unit test for the property 'TokenUnsuspendResponse'
        }

    }

}
