/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing TokenSuspendRequestSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TokenSuspendRequestSchemaTests
    {
        // TODO uncomment below to declare an instance variable for TokenSuspendRequestSchema
        //private TokenSuspendRequestSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenSuspendRequestSchema
            //instance = new TokenSuspendRequestSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenSuspendRequestSchema
        /// </summary>
        [Test]
        public void TokenSuspendRequestSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TokenSuspendRequestSchema
            //Assert.IsInstanceOfType<TokenSuspendRequestSchema> (instance, "variable 'instance' is a TokenSuspendRequestSchema");
        }


        /// <summary>
        /// Test the property 'TokenSuspendRequest'
        /// </summary>
        [Test]
        public void TokenSuspendRequestTest()
        {
            // TODO unit test for the property 'TokenSuspendRequest'
        }

    }

}
