/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YourApp.MdesCustomerClient.Api;
using YourApp.MdesCustomerClient.Model;
using YourApp.MdesCustomerClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YourApp.MdesCustomerClient.Test
{
    /// <summary>
    ///  Class for testing TokenUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TokenUpdateRequestTests
    {
        // TODO uncomment below to declare an instance variable for TokenUpdateRequest
        //private TokenUpdateRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenUpdateRequest
            //instance = new TokenUpdateRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenUpdateRequest
        /// </summary>
        [Test]
        public void TokenUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TokenUpdateRequest
            //Assert.IsInstanceOfType<TokenUpdateRequest> (instance, "variable 'instance' is a TokenUpdateRequest");
        }


        /// <summary>
        /// Test the property 'TokenUniqueReference'
        /// </summary>
        [Test]
        public void TokenUniqueReferenceTest()
        {
            // TODO unit test for the property 'TokenUniqueReference'
        }
        /// <summary>
        /// Test the property 'CurrentAccountPan'
        /// </summary>
        [Test]
        public void CurrentAccountPanTest()
        {
            // TODO unit test for the property 'CurrentAccountPan'
        }
        /// <summary>
        /// Test the property 'NewAccountPan'
        /// </summary>
        [Test]
        public void NewAccountPanTest()
        {
            // TODO unit test for the property 'NewAccountPan'
        }
        /// <summary>
        /// Test the property 'CurrentFinancialAccountInformation'
        /// </summary>
        [Test]
        public void CurrentFinancialAccountInformationTest()
        {
            // TODO unit test for the property 'CurrentFinancialAccountInformation'
        }
        /// <summary>
        /// Test the property 'NewFinancialAccountId'
        /// </summary>
        [Test]
        public void NewFinancialAccountIdTest()
        {
            // TODO unit test for the property 'NewFinancialAccountId'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'AccountPanSequenceNumber'
        /// </summary>
        [Test]
        public void AccountPanSequenceNumberTest()
        {
            // TODO unit test for the property 'AccountPanSequenceNumber'
        }
        /// <summary>
        /// Test the property 'IssuerProductConfigurationId'
        /// </summary>
        [Test]
        public void IssuerProductConfigurationIdTest()
        {
            // TODO unit test for the property 'IssuerProductConfigurationId'
        }
        /// <summary>
        /// Test the property 'UpdateWalletProviderIndicator'
        /// </summary>
        [Test]
        public void UpdateWalletProviderIndicatorTest()
        {
            // TODO unit test for the property 'UpdateWalletProviderIndicator'
        }
        /// <summary>
        /// Test the property 'CommentText'
        /// </summary>
        [Test]
        public void CommentTextTest()
        {
            // TODO unit test for the property 'CommentText'
        }
        /// <summary>
        /// Test the property 'ReasonCode'
        /// </summary>
        [Test]
        public void ReasonCodeTest()
        {
            // TODO unit test for the property 'ReasonCode'
        }
        /// <summary>
        /// Test the property 'AuditInfo'
        /// </summary>
        [Test]
        public void AuditInfoTest()
        {
            // TODO unit test for the property 'AuditInfo'
        }

    }

}
