/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YourApp.MdesCustomerClient.Client.OpenAPIDateConverter;

namespace YourApp.MdesCustomerClient.Model
{
    /// <summary>
    /// TokenUnsuspendResponseSchema
    /// </summary>
    [DataContract]
    public partial class TokenUnsuspendResponseSchema :  IEquatable<TokenUnsuspendResponseSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenUnsuspendResponseSchema" /> class.
        /// </summary>
        /// <param name="tokenUnsuspendResponse">tokenUnsuspendResponse.</param>
        public TokenUnsuspendResponseSchema(SimpleTokenResponse tokenUnsuspendResponse = default(SimpleTokenResponse))
        {
            this.TokenUnsuspendResponse = tokenUnsuspendResponse;
        }
        
        /// <summary>
        /// Gets or Sets TokenUnsuspendResponse
        /// </summary>
        [DataMember(Name="TokenUnsuspendResponse", EmitDefaultValue=false)]
        public SimpleTokenResponse TokenUnsuspendResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TokenUnsuspendResponseSchema {\n");
            sb.Append("  TokenUnsuspendResponse: ").Append(TokenUnsuspendResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TokenUnsuspendResponseSchema);
        }

        /// <summary>
        /// Returns true if TokenUnsuspendResponseSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of TokenUnsuspendResponseSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TokenUnsuspendResponseSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TokenUnsuspendResponse == input.TokenUnsuspendResponse ||
                    (this.TokenUnsuspendResponse != null &&
                    this.TokenUnsuspendResponse.Equals(input.TokenUnsuspendResponse))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TokenUnsuspendResponse != null)
                    hashCode = hashCode * 59 + this.TokenUnsuspendResponse.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
