/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YourApp.MdesCustomerClient.Client.OpenAPIDateConverter;

namespace YourApp.MdesCustomerClient.Model
{
    /// <summary>
    /// TokenActivateRequestSchema
    /// </summary>
    [DataContract]
    public partial class TokenActivateRequestSchema :  IEquatable<TokenActivateRequestSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenActivateRequestSchema" /> class.
        /// </summary>
        /// <param name="tokenActivateRequest">tokenActivateRequest.</param>
        public TokenActivateRequestSchema(TokenActivateRequest tokenActivateRequest = default(TokenActivateRequest))
        {
            this.TokenActivateRequest = tokenActivateRequest;
        }
        
        /// <summary>
        /// Gets or Sets TokenActivateRequest
        /// </summary>
        [DataMember(Name="TokenActivateRequest", EmitDefaultValue=false)]
        public TokenActivateRequest TokenActivateRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TokenActivateRequestSchema {\n");
            sb.Append("  TokenActivateRequest: ").Append(TokenActivateRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TokenActivateRequestSchema);
        }

        /// <summary>
        /// Returns true if TokenActivateRequestSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of TokenActivateRequestSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TokenActivateRequestSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TokenActivateRequest == input.TokenActivateRequest ||
                    (this.TokenActivateRequest != null &&
                    this.TokenActivateRequest.Equals(input.TokenActivateRequest))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TokenActivateRequest != null)
                    hashCode = hashCode * 59 + this.TokenActivateRequest.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
