/* 
 * MDES Customer Service
 *
 * This API provides our Issuer partners with resources to help resolve consumer queries about payment accounts enabled through our digitization platform.
 *
 * OpenAPI spec version: 2.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YourApp.MdesCustomerClient.Client.OpenAPIDateConverter;

namespace YourApp.MdesCustomerClient.Model
{
    /// <summary>
    /// UpdateTokenAssuranceRequestSchema
    /// </summary>
    [DataContract]
    public partial class UpdateTokenAssuranceRequestSchema :  IEquatable<UpdateTokenAssuranceRequestSchema>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateTokenAssuranceRequestSchema" /> class.
        /// </summary>
        /// <param name="updateTokenAssuranceRequest">updateTokenAssuranceRequest.</param>
        public UpdateTokenAssuranceRequestSchema(UpdateTokenAssuranceRequest updateTokenAssuranceRequest = default(UpdateTokenAssuranceRequest))
        {
            this.UpdateTokenAssuranceRequest = updateTokenAssuranceRequest;
        }
        
        /// <summary>
        /// Gets or Sets UpdateTokenAssuranceRequest
        /// </summary>
        [DataMember(Name="UpdateTokenAssuranceRequest", EmitDefaultValue=false)]
        public UpdateTokenAssuranceRequest UpdateTokenAssuranceRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateTokenAssuranceRequestSchema {\n");
            sb.Append("  UpdateTokenAssuranceRequest: ").Append(UpdateTokenAssuranceRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateTokenAssuranceRequestSchema);
        }

        /// <summary>
        /// Returns true if UpdateTokenAssuranceRequestSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateTokenAssuranceRequestSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateTokenAssuranceRequestSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UpdateTokenAssuranceRequest == input.UpdateTokenAssuranceRequest ||
                    (this.UpdateTokenAssuranceRequest != null &&
                    this.UpdateTokenAssuranceRequest.Equals(input.UpdateTokenAssuranceRequest))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UpdateTokenAssuranceRequest != null)
                    hashCode = hashCode * 59 + this.UpdateTokenAssuranceRequest.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
